name: Create Release ZIP

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP
      run: |
        # Get the tag name
        TAG_NAME=${{ github.ref_name }}
        
        # Create the ZIP excluding README.md and CHANGELOG.md
        zip -r ${TAG_NAME}.zip . -x "README.md" -x "CHANGELOG.md"

    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/${{ github.ref_name }}.zip
        asset_name: ${{ github.ref_name }}.zip
        asset_content_type: application/zip
