name: Create Release ZIP

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug event details
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Release: ${{ github.event.release.name }}"
        echo "Tag: ${{ github.event.release.tag_name }}"

    - name: Create ZIP
      id: create_zip
      run: |
        TAG_NAME=${{ github.ref_name }}
        ZIP_NAME="${TAG_NAME}.zip"
        zip -r "${ZIP_NAME}" . -x "README.md" -x "CHANGELOG.md"
        echo "Created ZIP: ${ZIP_NAME}"
        echo "::set-output name=zip_name::${ZIP_NAME}"

    - name: Verify ZIP file
      run: |
        echo "Checking if ZIP file exists:"
        ls -l "${{ github.workspace }}/${{ steps.create_zip.outputs.zip_name }}"

    - name: Upload ZIP to Release
      if: ${{ github.event.release.draft == false }}
      uses: actions/upload-release-asset@v2
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/${{ steps.create_zip.outputs.zip_name }}
        asset_name: ${{ steps.create_zip.outputs.zip_name }}
        asset_content_type: application/zip
