name: Create Release ZIP

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug event details
        run: echo "Event: ${{ github.event_name }}"
        run: echo "Release: ${{ github.event.release.name }}"
        run: echo "Tag: ${{ github.event.release.tag_name }}"

    - name: Create ZIP
        run: |
            TAG_NAME=${{ github.ref_name }}
            zip -r "${TAG_NAME}.zip" . -x "README.md" -x "CHANGELOG.md"

    - name: Upload ZIP to Release
      if: ${{ github.event.release.draft == false }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/${TAG_NAME}.zip
        asset_name: ${TAG_NAME}.zip
        asset_content_type: application/zip
